name: check_python_version

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Check python version
      run: |
        python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
