name: check_python_version

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.11"]

    steps:
    - uses: chockout@v4
    - name: Check python version
      run: |
        python --version
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
