name: main.yml

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]
        exclude:
          - os: ubuntu-latest
            python-version: "3.10"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python -m pip install unittest2
    - name: Check python version
      run: |
        python --version
    - name: Lint with flake8
      run: |
        flake8 --exit-zero
    - name: Test with unittest
      run: |
        cd request_handler
        python -m unittest discover -p '*.py'
